### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by Shane-Black** [learn-co-curriculum/javascript-first-class-functions#10]
http://javascriptissexy.com/understand-javascript-callback-functions-and-use-them/#more-1037

^ site cannot be reached

**Comment by graciemcguire** [comment]
Hey @Shane-Black! The link is working on my end... If the issue persists, please let us know, and I'd be happy to take a second look!
As always, thanks for contributing! 💙

**Comment by Shane-Black** [comment]
Just retried, definitely broken.


Kind regards,

Shane

On July 22, 2021, Ian Hollander ***@***.***> wrote:
> Hey @Shane-Black <https://github.com/Shane-Black>! The link is working
> on my end... If the issue persists, please let us know, and I'd be
> happy to take a second look!
>  As always, thanks for contributing! 💙
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/learn-co-curriculum/javascript-first-class-
functions/issues/10#issuecomment-884298185>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AUF4GZXNBIIJTZUO6U3UHJ3TY3ULNANCNFSM5AXEX2WQ>.
