### ISSUE TITLE
The tests on this lab don't reflect what is in the readme or solution

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/javascript-first-class-functions#6]
Hey,

I was helping a student with this lab and the test, regardless if run blank, from the students solution, or from the solution branch gave me the same errors that didn't reflect what the actual content of the lab was covering.

-Nick

@aturkewi

**Comment by AnnJohn** [comment]
cc @thomastuts

**Comment by thomastuts** [comment]
I'm not sure what those tests are supposed to actually test, but yeah, they expect some completely different code. I _think_ we can just ditch the tests here altogether since this is a reading lesson, those generally don't have tests in my experience.

**Comment by AnnJohn** [comment]
@NStephenson i see what the problem is. I don't this should have been a lab so I'll change to a Readme and update the lesson.
