### ISSUE TITLE
minor point, showing callback occurs in the order it appears in body of main function. Differs from README text.

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/javascript-first-class-functions#8]
Quote from the README states that a callback function happens   "...after the body of the function it is called in, completes".  
**********************snippet from README ***********************
Note: you'll often see functions used in this way referred to as "callbacks." That's because they're called back after the body of the function they're passed to completes! 
*******************************************************************

The attached PDF shows screenshots of callback function executing in the order it appears in the body of the function it is passed to: 

 
[CallBack Functions.pdf](https://github.com/learn-co-curriculum/javascript-first-class-functions/files/802315/CallBack.Functions.pdf)

**Comment by lizbur10** [comment]
Hey Brad!!! The lesson has been updated to address this issue. Thanks for contributing to the curriculum.

Cheers! 💙
